POST http://localhost:3001/api/notes
Content-Type: application/json
c
{
  "username": "puthyrathy",
  "private": false,
  "url": "https://www.paulgraham.com/foundermode.html",
  "content": "Brian Chesky is cool.",
  "date": null,
  "likes": 19
}