POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "sothyrithy",
  "name": "Soth Hy",
  "password": "goated"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "puthyrathy",
  "name": "Rath Hy",
  "password": "goated"
}